const express = require('express');
const http = require('http');
const crypto = require('crypto');
const path = require('path');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*' } });
const PORT = process.env.PORT || 3000;
const rooms = new Map();

const EVIDENCE = ['receipt','access card','alarm clock','antique coin','ashes','backpack','bandage','battery','button','boarding pass','business card','camera','candle','car key','coffee cup','concert ticket','credit card','diary','glove','envelope','eyeglasses','flash drive','flower petal','footprint','fountain pen','glass fragment','hair strand','handkerchief','hotel keycard','id badge','keychain','lighter','map','matchbook','medicine bottle','metro ticket','movie stub','name tag','newspaper clipping','notebook','parking ticket','passport photo','pendant','phone charger','playing card','postcard','power bank','printed email','scarf','shopping list','sim card','sunglasses','train ticket','usb cable','wallet photo','watch strap','work permit','necklace','broken watch','ripped note','plastic card','coin purse','paper clip','souvenir','photo strip'];
const MEANS = ['baseball bat','blunt stone','boiling liquid','broken bottle','cable strangulation','carbon monoxide','chemical burn','choking','crowbar','drowning','electric shock','falling object','fire','heavy statue','hunting knife','ice pick','injection','kitchen knife','metal pipe','poisoned drink','poisoned food','razor blade','rope','scissors','screwdriver','sharp glass','overdose','smoke inhalation','steel bar','suffocation','toxic gas','vehicle impact','wrench','acid','brick','car crash','hammer','live wire','nail gun','plastic wrap','pushed downstairs','rock','sedative','shovel','smothering','heavy book','metal cable','cleaning chemical','fall from height','crushing impact','heated object','wooden club','wire','gas leak','medication mix','sharp tool'];
const FIXED = [
  { title:'Cause of Death', options:['Suffocation','Severe Injury','Blood Loss','Illness','Poisoning','Accident'] },
  { title:'Location of Crime', options:['Restaurant','Hotel','Hospital','Construction Site','Bookstore','Bar'] }
];
const SCENES = [
  { title:'Corpse Condition', options:['Warm','Stiff','Decayed','Incomplete','Intact','Twisted'] },
  { title:'Time of Day', options:['Dawn','Morning','Noon','Afternoon','Evening','Midnight'] },
  { title:'Trace at Scene', options:['Powder','Liquid','Fiber','Print','Residue','None'] },
  { title:'Motive', options:['Money','Jealousy','Revenge','Fear','Secret','Unknown'] },
  { title:'Weather', options:['Clear','Cloudy','Rain','Storm','Windy','Humid'] },
  { title:'Victim Clothing', options:['Formal','Casual','Uniform','Nightwear','Sportswear','Damaged'] },
  { title:'Sound Nearby', options:['Argument','Crash','Music','Alarm','Footsteps','Silence'] },
  { title:'General Impression', options:['Planned','Sudden','Personal','Messy','Professional','Desperate'] },
  { title:'Body Position', options:['Face Up','Face Down','Seated','Curled','Hanging','Hidden'] },
  { title:'Suspicious Item', options:['Food','Drink','Medicine','Tool','Device','Document'] },
  { title:'Crime Timing', options:['Minutes Ago','Within Hour','Several Hours','Yesterday','Days Ago','Unclear'] },
  { title:'Scene Condition', options:['Clean','Disturbed','Burned','Wet','Dark','Crowded'] }
];
const BOT_PROFILES = [
  ['Mira','analytical'],['Theo','cautious'],['Luna','social'],['Jax','bold'],['Nico','analytical'],['Sage','skeptical'],['Iris','social'],['Rin','bold'],['Kai','chaotic'],['Zoe','analytical'],['Ash','quiet']
];

const id = (n=8) => crypto.randomBytes(n).toString('hex');
const pick = a => a[Math.floor(Math.random()*a.length)];
const later = (min,max,fn) => setTimeout(fn, Math.floor(min + Math.random()*(max-min)));
function shuffle(a){ const x=[...a]; for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [x[i],x[j]]=[x[j],x[i]];} return x; }
function safeName(v){ return String(v||'').trim().replace(/\s+/g,' ').slice(0,24)||'Player'; }
function roomCode(){ const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; let c; do c=Array.from({length:6},()=>pick(chars)).join(''); while(rooms.has(c)); return c; }
function log(room,text,type='system'){ room.log.push({id:id(4),text,type,at:Date.now()}); if(room.log.length>120) room.log.splice(0,room.log.length-120); }
function phase(room,name,seconds=0){ room.phase=name; room.phaseStartedAt=Date.now(); room.phaseEndsAt=seconds?Date.now()+seconds*1000:null; room.botPhaseKey=null; }
function tile(src,slot,fixed=false){ return {slot,fixed,title:src.title,options:[...src.options],marker:null}; }
function initialScene(){ const r=shuffle(SCENES).slice(0,4); return [tile(FIXED[0],0,true),tile(FIXED[1],1,true),...r.map((t,i)=>tile(t,i+2))]; }
function findRoom(socket,code){ const room=rooms.get(String(code||'').toUpperCase()); if(!room) throw Error('Room not found.'); const player=room.players.find(p=>!p.isBot&&p.socketId===socket.id); if(!player) throw Error('You are not connected to this room.'); return {room,player}; }

function privateState(room,p){ const x={role:p.role||null}; if((p.role==='Murderer'||p.role==='Forensic Scientist')&&room.solution)x.solution=room.solution; if(p.role==='Accomplice')x.murdererId=room.murdererId; if(p.role==='Witness')x.suspectIds=[room.murdererId,room.accompliceId].filter(Boolean); if(room.phase==='ended'&&room.solution)x.solution=room.solution; return x; }
function state(room,p){ return {code:room.code,gameId:room.gameId,phase:room.phase,round:room.round,phaseStartedAt:room.phaseStartedAt,phaseEndsAt:room.phaseEndsAt,hostId:room.hostId,meId:p.id,settings:room.settings,players:room.players.map(q=>({id:q.id,name:q.name,isBot:!!q.isBot,botStyle:q.isBot?q.botStyle:null,connected:q.isBot||!!q.socketId,role:room.phase==='ended'?q.role:null,solveUsed:!!q.solveUsed,finalDone:!!q.finalDone,finalAction:q.finalAction||null,evidence:q.role==='Forensic Scientist'?[]:q.evidence,means:q.role==='Forensic Scientist'?[]:q.means})),private:privateState(room,p),scene:room.scene,winner:room.winner,endingReason:room.endingReason,solvedBy:room.solvedBy||null,log:room.log}; }
function emit(room){ for(const p of room.players) if(!p.isBot&&p.socketId) io.to(p.socketId).emit('state',state(room,p)); }

function bot(room){ const used=new Set(room.players.map(p=>p.name.toLowerCase())); const prof=BOT_PROFILES.find(([n])=>!used.has(n.toLowerCase()))||[`Bot ${room.players.filter(p=>p.isBot).length+1}`,pick(['analytical','cautious','social','bold','skeptical','chaotic','quiet'])]; return {id:id(),name:prof[0],isBot:true,botStyle:prof[1],role:null,solveUsed:false,finalDone:false,finalAction:null,evidence:[],means:[],socketId:null,token:null}; }
function addBots(room,n){ const count=Math.min(Math.max(Number(n)||0,0),12-room.players.length); for(let i=0;i<count;i++)room.players.push(bot(room)); return count; }
function dealCards(room){ const e=shuffle(EVIDENCE),m=shuffle(MEANS),n=room.settings.cardsPerType; let ei=0,mi=0; for(const p of room.players){ if(p.role==='Forensic Scientist'){p.evidence=[];p.means=[];continue;} p.evidence=e.slice(ei,ei+n).map((text,i)=>({id:`e_${p.id}_${i}`,text})); p.means=m.slice(mi,mi+n).map((text,i)=>({id:`m_${p.id}_${i}`,text})); ei+=n;mi+=n; } }
function start(room){ if(room.players.length<4) throw Error('At least 4 players or bots are required.'); const ids=shuffle(room.players.map(p=>p.id)); room.forensicId=ids[0];room.murdererId=ids[1];room.accompliceId=room.players.length>=6?ids[2]:null;room.witnessId=room.players.length>=6?ids[3]:null; for(const p of room.players){p.role=p.id===room.forensicId?'Forensic Scientist':p.id===room.murdererId?'Murderer':p.id===room.accompliceId?'Accomplice':p.id===room.witnessId?'Witness':'Investigator';p.solveUsed=false;p.finalDone=false;p.finalAction=null;} dealCards(room); room.gameId=id(5);room.round=0;room.scene=[];room.solution=null;room.winner=null;room.endingReason=null;room.solvedBy=null;room.usedSceneTitles=[]; phase(room,'crime',90); log(room,'Secret roles have been dealt. The Murderer is choosing the crime.'); emit(room); scheduleBots(room); }
function reset(room){ room.round=0;room.scene=[];room.solution=null;room.winner=null;room.endingReason=null;room.solvedBy=null;room.forensicId=room.murdererId=room.accompliceId=room.witnessId=null;room.usedSceneTitles=[]; for(const p of room.players)Object.assign(p,{role:null,solveUsed:false,finalDone:false,finalAction:null,evidence:[],means:[]}); phase(room,'lobby'); log(room,'Rematch lobby opened.'); }

function typeOfMeans(t=''){ const s=t.toLowerCase(); if(/poison|toxic|overdose|sedative|medication|carbon monoxide|gas leak/.test(s))return'poison'; if(/strang|choking|suffocation|smother|plastic wrap|drowning|smoke/.test(s))return'suffocation'; if(/knife|razor|scissors|ice pick|sharp|glass|nail gun|screwdriver/.test(s))return'sharp'; if(/fire|boiling|heated|chemical burn|acid|electric|live wire/.test(s))return'burn'; if(/car crash|vehicle|fall|pushed|crushing|falling object/.test(s))return'accident'; return'blunt'; }
function typeOfEvidence(t=''){ const s=t.toLowerCase(); if(/medicine|bandage/.test(s))return'Medicine'; if(/coffee|bottle/.test(s))return'Drink'; if(/phone|camera|usb|flash drive|power bank|charger|sim card|battery/.test(s))return'Device'; if(/receipt|ticket|pass|card|email|note|newspaper|permit|passport|map|diary|notebook|list/.test(s))return'Document'; return'Tool'; }
function forensicChoice(room,t){ const mt=typeOfMeans(room.solution?.meansText),et=typeOfEvidence(room.solution?.evidenceText); if(t.title==='Cause of Death')return({poison:'Poisoning',suffocation:'Suffocation',sharp:'Blood Loss',burn:'Severe Injury',accident:'Accident',blunt:'Severe Injury'})[mt]; if(t.title==='Suspicious Item'&&t.options.includes(et))return et; if(t.title==='Trace at Scene'){if(mt==='sharp')return'Liquid';if(mt==='suffocation')return'Fiber';if(mt==='poison')return pick(['Powder','Liquid','Residue']);if(mt==='burn')return'Residue';} if(t.title==='Scene Condition'&&mt==='burn')return'Burned'; if(t.title==='General Impression'){if(mt==='poison')return pick(['Planned','Professional']);if(mt==='sharp')return pick(['Personal','Messy']);if(mt==='accident')return'Sudden';} return pick(t.options); }
function score(room,e,m){ let s=Math.random()*1.5; const markers=Object.fromEntries(room.scene.filter(t=>t.marker).map(t=>[t.title,t.marker])); const mt=typeOfMeans(m),et=typeOfEvidence(e); const exp=({poison:'Poisoning',suffocation:'Suffocation',sharp:'Blood Loss',burn:'Severe Injury',accident:'Accident',blunt:'Severe Injury'})[mt]; if(markers['Cause of Death'])s+=markers['Cause of Death']===exp?6:-1; if(markers['Suspicious Item']===et)s+=3; if(markers['Trace at Scene']==='Liquid'&&mt==='sharp')s+=2; if(markers['Trace at Scene']==='Fiber'&&mt==='suffocation')s+=2; return s; }
function best(room,b){ const list=[]; for(const p of room.players){ if(p.role==='Forensic Scientist'||p.id===b.id)continue; for(const e of p.evidence)for(const m of p.means){let sc=score(room,e.text,m.text); if(b.role==='Witness'&&[room.murdererId,room.accompliceId].includes(p.id))sc+=4;if(['Murderer','Accomplice'].includes(b.role)&&p.id===room.murdererId)sc-=8;if(b.botStyle==='chaotic')sc+=Math.random()*4-2;if(b.botStyle==='analytical')sc+=.8;list.push({target:p,evidence:e,means:m,score:sc});}} return list.sort((a,b)=>b.score-a.score)[0]; }
function botTalk(room,b){ const x=best(room,b); if(!x)return'I need another clue before I commit.'; const n=x.target.name,m=x.means.text,e=x.evidence.text; const t={analytical:[`I'm matching the clue board to the cards. ${n}'s ${e} + ${m} is a strong fit.`,`Right now ${n} has the cleanest clue match for me.`],cautious:[`I'm leaning ${n}, but I'm not ready to burn my badge yet.`,`I want to keep ${n} on the shortlist and hear everyone else first.`],social:[`What do you all think about ${n}? The ${m} stands out to me.`,`Can someone sanity-check ${n}'s cards with me?`],bold:[`${n} is my main suspect right now.`,`I'm pretty convinced ${n} deserves the most pressure.`],skeptical:[`I'm not sold on the obvious read. Still, ${n} is the best fit I see.`,`I think we're missing something, but ${n} is where I'd look first.`],chaotic:[`Wild thought: ${n}. The ${e} is giving me bad vibes.`,`I changed my mind twice, but I keep circling back to ${n}.`],quiet:[`My current lean is ${n}.`,`I'm watching ${n} for now.`]}; return pick(t[b.botStyle]||t.cautious); }
function allSpent(room){return room.players.filter(p=>p.role!=='Forensic Scientist').every(p=>p.solveUsed);}
function finalSetup(room){for(const p of room.players){if(p.role==='Forensic Scientist'){p.finalDone=true;p.finalAction=null;}else if(p.solveUsed){p.finalDone=true;p.finalAction='badge-spent';}else{p.finalDone=false;p.finalAction=null;}}}
function finalComplete(room){return room.players.filter(p=>p.role!=='Forensic Scientist').every(p=>p.finalDone);}
function closeFinal(room){if(room.phase==='final'&&finalComplete(room)){phase(room,'ended');room.winner='Murderer Team';room.endingReason='Final Discussion ended without an exact solution. The Murderer Team escaped.';log(room,'All final decisions are locked. The Murderer Team wins.');emit(room);return true;}return false;}
function accuse(room,p,target,e,m){p.solveUsed=true;if(room.phase==='final'){p.finalDone=true;p.finalAction='accuse';} const correct=room.solution&&target.id===room.solution.ownerId&&e.id===room.solution.evidenceId&&m.id===room.solution.meansId; if(correct){room.solvedBy=p.id;if(room.witnessId){phase(room,'reversal',45);log(room,`${p.name} solved the crime! The Murderer gets one chance to identify the Witness.`);}else{phase(room,'ended');room.winner='Investigators';room.endingReason=`${p.name} found the exact suspect, Evidence, and Means.`;log(room,'Investigators solved the case.');}}else{log(room,`${p.name} used a Solve Crime badge — incorrect accusation.`); if(room.phase==='final')closeFinal(room);else if(allSpent(room)){phase(room,'ended');room.winner='Murderer Team';room.endingReason='Every Solve Crime badge was spent without finding the exact solution.';log(room,'All badges are spent. The Murderer Team wins.');}} emit(room);scheduleBots(room);}

function scheduleBots(room){ const key=`${room.gameId}:${room.phase}:${room.round}`; if(room.botPhaseKey===key)return;room.botPhaseKey=key;
  if(room.phase==='crime'){const b=room.players.find(p=>p.id===room.murdererId&&p.isBot);if(b)later(1200,2600,()=>{if(room.phase!=='crime')return;const e=pick(b.evidence),m=pick(b.means);room.solution={ownerId:b.id,evidenceId:e.id,evidenceText:e.text,meansId:m.id,meansText:m.text};room.scene=initialScene();room.usedSceneTitles=room.scene.map(t=>t.title);phase(room,'forensic',90);log(room,'The Murderer locked in the secret crime.');emit(room);scheduleBots(room);});return;}
  if(room.phase==='forensic'){const b=room.players.find(p=>p.id===room.forensicId&&p.isBot);if(b){room.scene.filter(t=>!t.marker).forEach((t,i)=>later(700+i*550,1100+i*700,()=>{if(room.phase!=='forensic'||t.marker)return;t.marker=forensicChoice(room,t);log(room,`${b.name} placed a clue marker on ${t.title}.`);if(room.scene.every(x=>x.marker)){if(!room.round)room.round=1;phase(room,'discussion',room.settings.discussionTimerSec);log(room,`Investigation Round ${room.round} begins.`);}emit(room);scheduleBots(room);}));}return;}
  if(['discussion','final'].includes(room.phase)){const bots=shuffle(room.players.filter(p=>p.isBot&&p.role!=='Forensic Scientist'));bots.forEach((b,i)=>later(1000+i*650,1600+i*1000,()=>{if(`${room.gameId}:${room.phase}:${room.round}`!==key)return;log(room,`${b.name}: ${botTalk(room,b)}`,'chat');emit(room);})); if(room.phase==='final'){bots.forEach((b,i)=>later(5000+i*900,8500+i*1500,()=>{if(room.phase!=='final'||b.finalDone)return;const x=best(room,b);const chance=b.botStyle==='bold'?.78:b.botStyle==='cautious'?.48:.62;if(x&&x.score>5&&Math.random()<chance){log(room,`${b.name}: I'm locking my final accusation on ${x.target.name}: ${x.evidence.text} + ${x.means.text}.`,'chat');accuse(room,b,x.target,x.evidence,x.means);}else{b.finalDone=true;b.finalAction='pass';log(room,`${b.name} passed in Final Discussion.`);if(!closeFinal(room))emit(room);}}));}else{bots.forEach((b,i)=>later(6500+i*1200,10000+i*1700,()=>{if(room.phase!=='discussion'||b.solveUsed)return;const x=best(room,b);let c=room.round===1?.05:room.round===2?.15:.32;if(b.botStyle==='bold')c+=.15;if(b.botStyle==='cautious')c-=.07;if(x&&x.score>6&&Math.random()<c){log(room,`${b.name}: I'm spending my badge on ${x.target.name}.`,'chat');accuse(room,b,x.target,x.evidence,x.means);}}));}return;}
  if(room.phase==='reversal'){const b=room.players.find(p=>p.id===room.murdererId&&p.isBot);if(b)later(2200,4200,()=>{if(room.phase!=='reversal')return;const choices=room.players.filter(p=>p.role!=='Forensic Scientist'&&p.id!==b.id);let target=pick(choices);if(room.witnessId&&Math.random()<.35)target=room.players.find(p=>p.id===room.witnessId)||target;phase(room,'ended');if(target.id===room.witnessId){room.winner='Murderer Team';room.endingReason=`${b.name} correctly identified ${target.name} as the Witness.`;log(room,'The Murderer found the Witness and stole the victory.');}else{room.winner='Investigators';room.endingReason='The Murderer guessed the wrong Witness.';log(room,'The Witness stayed hidden. Investigators keep the victory.');}emit(room);});}
}

function newHuman(name,socket){return{id:id(),token:id(16),socketId:socket.id,name:safeName(name),isBot:false,role:null,solveUsed:false,finalDone:false,finalAction:null,evidence:[],means:[]};}
function roomTemplate(code,host){return{code,gameId:null,hostId:host.id,players:[host],phase:'lobby',round:0,phaseStartedAt:Date.now(),phaseEndsAt:null,scene:[],solution:null,winner:null,endingReason:null,solvedBy:null,forensicId:null,murdererId:null,accompliceId:null,witnessId:null,usedSceneTitles:[],botPhaseKey:null,settings:{cardsPerType:4,discussionTimerSec:90},log:[]};}

io.on('connection',socket=>{
  socket.on('createRoom',(x,cb=()=>{})=>{try{const p=newHuman(x?.name,socket),code=roomCode(),room=roomTemplate(code,p);rooms.set(code,room);socket.join(code);log(room,`${p.name} created the table.`);const n=addBots(room,Math.min(11,Math.max(0,Number(x?.botCount)||0)));if(n)log(room,`${n} bot${n===1?'':'s'} joined the table.`);cb({ok:true,code,token:p.token,playerId:p.id});emit(room);}catch(e){cb({ok:false,error:e.message});}});
  socket.on('joinRoom',(x,cb=()=>{})=>{try{const code=String(x?.code||'').trim().toUpperCase(),room=rooms.get(code);if(!room)throw Error('Room code not found.');if(room.phase!=='lobby')throw Error('This game has already started.');if(room.players.length>=12)throw Error('This room is full.');const name=safeName(x?.name);if(room.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))throw Error('That name is already used in this room.');const p=newHuman(name,socket);room.players.push(p);socket.join(code);log(room,`${p.name} joined the table.`);cb({ok:true,code,token:p.token,playerId:p.id});emit(room);}catch(e){cb({ok:false,error:e.message});}});
  socket.on('resumeRoom',(x,cb=()=>{})=>{try{const room=rooms.get(String(x?.code||'').toUpperCase());if(!room)throw Error('Room no longer exists.');const p=room.players.find(p=>!p.isBot&&p.token===x?.token);if(!p)throw Error('Could not restore this player.');p.socketId=socket.id;socket.join(room.code);cb({ok:true,code:room.code,playerId:p.id});emit(room);}catch(e){cb({ok:false,error:e.message});}});
  socket.on('leaveRoom',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='lobby')throw Error('You cannot leave after the game starts.');room.players=room.players.filter(p=>p.id!==player.id);socket.leave(room.code);const humans=room.players.filter(p=>!p.isBot);if(!humans.length)return rooms.delete(room.code);if(room.hostId===player.id)room.hostId=humans[0].id;log(room,`${player.name} left the room.`);emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('addBot',x=>{try{const{room,player}=findRoom(socket,x?.code);if(player.id!==room.hostId||room.phase!=='lobby')throw Error('Only the host can add bots in the lobby.');if(room.players.length>=12)throw Error('Room is full.');const b=bot(room);room.players.push(b);log(room,`${b.name} joined as a ${b.botStyle} bot.`);emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('fillBots',x=>{try{const{room,player}=findRoom(socket,x?.code);if(player.id!==room.hostId||room.phase!=='lobby')throw Error('Only the host can add bots in the lobby.');const target=Math.min(12,Math.max(4,Number(x?.target)||6));const n=addBots(room,target-room.players.length);if(n)log(room,`${n} bot${n===1?'':'s'} joined the table.`);emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('removeBot',x=>{try{const{room,player}=findRoom(socket,x?.code);if(player.id!==room.hostId||room.phase!=='lobby')throw Error('Only the host can remove bots in the lobby.');const b=room.players.find(p=>p.id===x?.botId&&p.isBot);if(!b)throw Error('Bot not found.');room.players=room.players.filter(p=>p.id!==b.id);log(room,`${b.name} left the table.`);emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('updateSettings',x=>{try{const{room,player}=findRoom(socket,x?.code);if(player.id!==room.hostId||room.phase!=='lobby')throw Error('Only the host can change lobby settings.');if(x.cardsPerType!==undefined){const n=Number(x.cardsPerType);if(![3,4,5].includes(n))throw Error('Invalid card count.');room.settings.cardsPerType=n;}if(x.discussionTimerSec!==undefined){const n=Number(x.discussionTimerSec);if(![0,60,90,120].includes(n))throw Error('Invalid timer.');room.settings.discussionTimerSec=n;}emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('startGame',x=>{try{const{room,player}=findRoom(socket,x?.code);if(player.id!==room.hostId||room.phase!=='lobby')throw Error('Only the host can start from the lobby.');start(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('chooseCrime',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='crime'||player.id!==room.murdererId)throw Error('Only the Murderer can choose the crime now.');const e=player.evidence.find(c=>c.id===x?.evidenceId),m=player.means.find(c=>c.id===x?.meansId);if(!e||!m)throw Error('Choose one Evidence and one Means card.');room.solution={ownerId:player.id,evidenceId:e.id,evidenceText:e.text,meansId:m.id,meansText:m.text};room.scene=initialScene();room.usedSceneTitles=room.scene.map(t=>t.title);phase(room,'forensic',90);log(room,'The secret crime is locked.');emit(room);scheduleBots(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('placeMarker',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='forensic'||player.id!==room.forensicId)throw Error('Only the Forensic Scientist can place markers.');const t=room.scene.find(t=>t.slot===Number(x?.slot));if(!t||t.marker||!t.options.includes(x?.value))throw Error('Invalid marker choice.');t.marker=x.value;if(room.scene.every(t=>t.marker)){if(!room.round)room.round=1;phase(room,'discussion',room.settings.discussionTimerSec);log(room,`Investigation Round ${room.round} begins.`);}emit(room);scheduleBots(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('advanceRound',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='discussion')throw Error('There is no next investigation round from this phase.');if(player.id!==room.hostId&&player.id!==room.forensicId)throw Error('Only the host or Forensic Scientist can advance.');if(room.round<3){room.round++;const available=SCENES.filter(t=>!room.usedSceneTitles.includes(t.title));const r=pick(available.length?available:SCENES),target=pick(room.scene.filter(t=>!t.fixed));room.scene[room.scene.findIndex(t=>t.slot===target.slot)]=tile(r,target.slot);room.usedSceneTitles.push(r.title);phase(room,'forensic',90);log(room,`Round ${room.round}: one clue tile was replaced.`);}else{finalSetup(room);phase(room,'final',75);log(room,'Final Discussion opened. Round 4 is locked out. Every eligible player must accuse or pass.');}emit(room);scheduleBots(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('passFinal',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='final'||player.role==='Forensic Scientist'||player.finalDone)throw Error('That final decision is not available.');player.finalDone=true;player.finalAction='pass';log(room,`${player.name} passed in Final Discussion.`);if(!closeFinal(room))emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('accuse',x=>{try{const{room,player}=findRoom(socket,x?.code);if(!['forensic','discussion','final'].includes(room.phase)||player.role==='Forensic Scientist'||player.solveUsed)throw Error('You cannot accuse now.');const target=room.players.find(p=>p.id===x?.targetId);if(!target||target.role==='Forensic Scientist')throw Error('Choose a valid suspect.');const e=target.evidence.find(c=>c.id===x?.evidenceId),m=target.means.find(c=>c.id===x?.meansId);if(!e||!m)throw Error('Choose one Evidence and one Means from the same suspect.');accuse(room,player,target,e,m);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('guessWitness',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='reversal'||player.id!==room.murdererId)throw Error('Only the Murderer can guess the Witness.');const target=room.players.find(p=>p.id===x?.targetId);if(!target||target.role==='Forensic Scientist')throw Error('Choose a player.');phase(room,'ended');if(target.id===room.witnessId){room.winner='Murderer Team';room.endingReason=`The Murderer correctly identified ${target.name} as the Witness.`;log(room,'The Murderer found the Witness and stole the victory.');}else{room.winner='Investigators';room.endingReason='The Murderer guessed the wrong Witness.';log(room,'The Witness stayed hidden. Investigators keep the victory.');}emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('chatMessage',x=>{try{const{room,player}=findRoom(socket,x?.code),text=String(x?.text||'').trim().slice(0,280);if(!text)return;if(player.role==='Forensic Scientist'&&!['lobby','ended'].includes(room.phase))throw Error('The Forensic Scientist communicates only through clue markers.');log(room,`${player.name}: ${text}`,'chat');emit(room);if(['discussion','final'].includes(room.phase)){const bots=room.players.filter(p=>p.isBot&&p.role!=='Forensic Scientist');if(bots.length)later(900,2200,()=>{if(!['discussion','final'].includes(room.phase))return;const b=pick(bots);log(room,`${b.name}: ${botTalk(room,b)}`,'chat');emit(room);});}}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('rematch',x=>{try{const{room,player}=findRoom(socket,x?.code);if(room.phase!=='ended'||player.id!==room.hostId)throw Error('Only the host can open a rematch after the game ends.');reset(room);emit(room);}catch(e){socket.emit('toast',{type:'error',message:e.message});}});
  socket.on('disconnect',()=>{for(const room of rooms.values()){const p=room.players.find(p=>!p.isBot&&p.socketId===socket.id);if(!p)continue;p.socketId=null;log(room,`${p.name} disconnected. They can return from the same browser.`);emit(room);break;}});
});

setInterval(()=>{for(const room of rooms.values()){if(!room.phaseEndsAt||Date.now()<room.phaseEndsAt)continue;if(room.phase==='discussion'){if(room.round>=3){finalSetup(room);phase(room,'final',75);log(room,'Discussion timer ended. Final Discussion is now locked in.');emit(room);scheduleBots(room);}else{room.phaseEndsAt=null;emit(room);}}else if(room.phase==='final'){for(const p of room.players.filter(p=>p.isBot&&!p.finalDone)){p.finalDone=true;p.finalAction='pass';log(room,`${p.name} passed as the Final Discussion timer expired.`);}room.phaseEndsAt=null;if(!closeFinal(room))emit(room);}else{room.phaseEndsAt=null;emit(room);}}},1000);

app.use(express.static(path.join(__dirname,'public')));
app.get('/health',(_req,res)=>res.json({ok:true,rooms:rooms.size,bots:true,version:'tabletop-live-v4'}));
app.get('*',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
server.listen(PORT,'0.0.0.0',()=>console.log(`Casefile Tabletop Live listening on ${PORT}`));
